---
# ------------------------------------------------------------------------------
# Playbook for implementing the configuration for the
#   "Cert Prep: Red Hat Certified System Engineer (EX300)" course
# ------------------------------------------------------------------------------

- hosts:                all

  tasks:

# ------------------------------------------------------------------------------
# Chapter 1: Virtual Systems Configuration
# ------------------------------------------------------------------------------

  - name:               "Install the 'Development tools' package group"
    dnf:
      name:             "@Development tools"
      state:            present
    become:             yes
    become_user:        root
    register:           install_dev_tools

# ------------------------------------------------------------------------------
# Chapter 2: System Configuration
# ------------------------------------------------------------------------------

  - name:               "Install sysstat"
    dnf:
      name:             sysstat
      state:            present
    become:             yes
    become_user:        root
    register:           install_sysstat

  - name:               "Ensure sysstat is enabled and started"
    systemd:
      name:             sysstat
      enabled:          yes
      state:            started
    become:             yes
    become_user:        root

  - name:               "Copy sample user logging script"
    copy:
      dest:             /root/bin/
      src:              userlog.sh
    become:             yes
    become_user:        root

  - name:               "Run sample user logging script every ten (10) mins"
    cron:
      name:             "Sample user logging"
      minute:           "*/10"
      job:              "/root/bin/userlog.sh"
      state:            present
    become:             yes
    become_user:        root

...
