---
# ------------------------------------------------------------------------------
# Playbook for implementing the configuration for the
#   "Cert Prep: Red Hat Certified System Engineer (EX300)" course
# ------------------------------------------------------------------------------

- hosts:                all

  tasks:

# ------------------------------------------------------------------------------
# Chapter 1: Virtual Systems Configuration
# ------------------------------------------------------------------------------

  - name:               "Install the 'Development tools' package group"
    dnf:
      name:             "@Development tools"
      state:            present
    become:             yes
    become_user:        root
    tags:               chapter_1

# ------------------------------------------------------------------------------
# Chapter 2: System Configuration
# ------------------------------------------------------------------------------

  - name:               "Chapter 2: System Configuration"
    block:

    - name:             "Install sysstat"
      dnf:
        name:           sysstat
        state:          present

    - name:             "Ensure sysstat is enabled and started"
      systemd:
        name:           sysstat
        enabled:        yes
        state:          started

    - name:             "Copy sample user logging script"
      copy:
        dest:           /root/bin/
        src:            userlog.sh

    - name:             "Run sample user logging script every ten (10) mins"
      cron:
        name:           "Sample user logging"
        minute:         "*/10"
        job:            "/root/bin/userlog.sh"
        state:          present

    become:             yes
    become_user:        root
    tags:               chapter_2

# ------------------------------------------------------------------------------
# Chapter 3: ISCSI Target Configuration
# ------------------------------------------------------------------------------

  - name:               "Chapter 3: ISCSI Target Configuration"
    block:

    - name:             "Install targetcli on iSCSI target"
      dnf:
        name:           targetcli
        state:          present
      when:             iscsi_role == "target"

    - name:             "Ensure iSCSI target is enabled and started"
      systemd:
        name:           target
        enabled:        yes
        state:          started
      when:             iscsi_role == "target"

    - name:             "Install iscsi-initiator-utils on iSCSI client"
      dnf:
        name:           iscsi-initiator-utils
        state:          present
      when:             iscsi_role == "client"

    - name:             "Ensure iSCSI daemon is enabled and started"
      systemd:
        name:           iscsid
        enabled:        yes
        state:          started
      when:             iscsi_role == "client"

    - name:             "Ensure iSCSI service is enabled and started"
      systemd:
        name:           iscsi
        enabled:        yes
        state:          started
      when:             iscsi_role == "client"

    - name:             "Create iSCSI target"
      script:
        cmd:            create_iscsi_lun.sh
      register:         create_iscsi_lun
      changed_when:
        -               create_iscsi_lun.stdout is defined
        -               '"Added " in create_iscsi_lun.stdout'
      when:             iscsi_role == "target"

    - name:             "Display output from create iSCSI target"
      debug:
        var:            create_iscsi_lun.stdout_lines
      when:             create_iscsi_lun.stdout_lines is defined

    - name:             "Configure firewalld"
      firewalld:
        immediate:      yes
        permanent:      yes
        service:        iscsi-target
        state:          enabled
      when:             iscsi_role == "target"

    - name:             "Set initiator name for client"
      lineinfile:
        path:           /etc/iscsi/initiatorname.iscsi
        regexp:         "^InitiatorName="
        line:           "InitiatorName=iqn.2021-05.au.id.yaocm:client1"
        state:          present
      when:             iscsi_role == "client"
      notify:           "Restart iSCSI initiator"

    - name:             "Turn on CHAP Authentication"
      lineinfile:
        path:           /etc/iscsi/iscsid.conf
        line:           "{{ item }}"
        state:          present
      when:             iscsi_role == "client"
      notify:           "Restart iSCSI initiator"
      loop:
        -               "node.session.auth.authmethod = CHAP"
        -               "node.session.auth.username = user1"
        -               "node.session.auth.password = password"

    - name:             "Install gdisk on iSCSI client"
      dnf:
        name:           gdisk
        state:          present
      when:             iscsi_role == "client"

    - name:            "Format iSCSI LUN"
      script:
        cmd:            format_file1_iscsi_lun.sh
      register:         format_file1_iscsi_lun
      changed_when:
        -               format_file1_iscsi_lun.stdout is defined
        -               '"Added " in format_file1_iscsi_lun.stdout'
      when:             iscsi_role == "client"

    - name:             "Display output from format iSCSI LUN"
      debug:
        var:            format_file1_iscsi_lun.stdout_lines
      when:             format_file1_iscsi_lun.stdout_lines is defined

    become:             yes
    become_user:        root
    tags:               chapter_3

# ------------------------------------------------------------------------------
# Chapter 4: NTP Services
# ------------------------------------------------------------------------------

  - name:               "Chapter 4: NTP Services"
    block:
    
    - name:             "Install Chrony"
      dnf:
        name:           chrony
        state:          present

    - name:             "Enable and start Chronyd"
      systemd:
        name:           chronyd
        state:          started
        enabled:        yes

    - name:             "Allow NTP queries from local server"
      lineinfile:
        path:           /etc/chrony.conf
        regexp:         "^allow"
        line:           "allow 192.168.1.0/24"
        state:          present
      notify:           "Restart chronyd"
      when:             ntp_role == "server"

    - name:             "Direct NTP queries to local server"
      lineinfile:
        path:           /etc/chrony.conf
        regexp:         "{{ item.regexp }}"
        line:           "{{ item.line }}"
        state:          present
      notify:           "Restart chronyd"
      loop:
        - { regexp: "^pool", line: "#pool" }
        - { regexp: "^server", line: "server 192.168.1.119 iburst" }
      when:             ntp_role == "client"

    - name:             "Allow NTP through Firewall"
      firewalld:
        immediate:      yes
        permanent:      yes
        service:        ntp
        state:          enabled
        zone:           public
      when:             ntp_role == "server"

    - name:             "Force all notified handlers"
      meta:             flush_handlers

    - name:             "Enable ntp queries"
      command:
        cmd:            "timedatectl set-ntp true"
      when:             ntp_role == "client"

    - name:             "Display ntp client status"
      command:
        cmd:            "chronyc sources -v"
      register:         disp_ntp_clt_status
      when:             ntp_role == "client"

    - name:             "Display ntp client status output"
      debug:
        var:            disp_ntp_clt_status.stdout_lines
      when:             disp_ntp_clt_status.stdout_lines is defined

    become:             yes
    become_user:        root
    tags:               chapter_4

# ------------------------------------------------------------------------------
# Chapter 5: Authentication Services
# ------------------------------------------------------------------------------

  - name:               "Chapter 5: Authentication Services"
    block:


    become:             yes
    become_user:        root
    tags:               chapter_5

# ------------------------------------------------------------------------------
# Chapter 6: Network Services
# ------------------------------------------------------------------------------

  - name:               "Chapter 6: Network Services"
    block:


    become:             yes
    become_user:        root
    tags:               chapter_6

# ------------------------------------------------------------------------------
# Chapter 7: Database Services
# ------------------------------------------------------------------------------

  - name:               "Chapter 7: Database Services"
    block:


    become:             yes
    become_user:        root
    tags:               chapter_7

# ------------------------------------------------------------------------------
# Chapter 8: DNS Services
# ------------------------------------------------------------------------------

  - name:               "Chapter 8: DNS Services"
    block:


    become:             yes
    become_user:        root
    tags:               chapter_8

# ------------------------------------------------------------------------------
# Chapter 9: Web Services
# ------------------------------------------------------------------------------

  - name:               "Chapter 9: Web Services"
    block:


    become:             yes
    become_user:        root
    tags:               chapter_9

# ------------------------------------------------------------------------------
# Chapter 10: NFS Services
# ------------------------------------------------------------------------------

  - name:               "Chapter 10: NFS Services"
    block:


    become:             yes
    become_user:        root
    tags:               chapter_10

# ------------------------------------------------------------------------------
# Chapter 11: SMB Services
# ------------------------------------------------------------------------------

  - name:               "Chapter 11: SMB Services"
    block:


    become:             yes
    become_user:        root
    tags:               chapter_11

# ------------------------------------------------------------------------------
# Chapter 12: SMTP Services
# ------------------------------------------------------------------------------

  - name:               "Chapter 12: SMTP Services"
    block:


    become:             yes
    become_user:        root
    tags:               chapter_12

# ------------------------------------------------------------------------------
# Chapter 13: SSH Services
# ------------------------------------------------------------------------------

  - name:               "Chapter 13: SSH Services"
    block:


    become:             yes
    become_user:        root
    tags:               chapter_13

# ------------------------------------------------------------------------------
# Handlers
# ------------------------------------------------------------------------------

  handlers:
  
  - name:               "Restart iSCSI initiator"
    systemd:
      name:             "{{ item }}"
      state:            restarted
    loop:
      -                 iscsi
      -                 iscsid
    become:             yes
    become_user:        root
  
  - name:               "Restart chronyd"
    systemd:
      name:             chronyd
      state:            restarted
    become:             yes
    become_user:        root
...
